// Generated by gencpp from file inverse_kinematics/GoalPosition.msg
// DO NOT EDIT!


#ifndef INVERSE_KINEMATICS_MESSAGE_GOALPOSITION_H
#define INVERSE_KINEMATICS_MESSAGE_GOALPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inverse_kinematics
{
template <class ContainerAllocator>
struct GoalPosition_
{
  typedef GoalPosition_<ContainerAllocator> Type;

  GoalPosition_()
    : x(0.0)
    , y(0.0)  {
    }
  GoalPosition_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::inverse_kinematics::GoalPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inverse_kinematics::GoalPosition_<ContainerAllocator> const> ConstPtr;

}; // struct GoalPosition_

typedef ::inverse_kinematics::GoalPosition_<std::allocator<void> > GoalPosition;

typedef boost::shared_ptr< ::inverse_kinematics::GoalPosition > GoalPositionPtr;
typedef boost::shared_ptr< ::inverse_kinematics::GoalPosition const> GoalPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inverse_kinematics::GoalPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inverse_kinematics::GoalPosition_<ContainerAllocator1> & lhs, const ::inverse_kinematics::GoalPosition_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inverse_kinematics::GoalPosition_<ContainerAllocator1> & lhs, const ::inverse_kinematics::GoalPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inverse_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inverse_kinematics::GoalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inverse_kinematics::GoalPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inverse_kinematics::GoalPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::inverse_kinematics::GoalPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inverse_kinematics/GoalPosition";
  }

  static const char* value(const ::inverse_kinematics::GoalPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::inverse_kinematics::GoalPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inverse_kinematics::GoalPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inverse_kinematics::GoalPosition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INVERSE_KINEMATICS_MESSAGE_GOALPOSITION_H
