(cl:defpackage dynamixel_ros_control-msg
  (:use )
  (:export
   "<HOMINGACTION>"
   "HOMINGACTION"
   "<HOMINGACTIONFEEDBACK>"
   "HOMINGACTIONFEEDBACK"
   "<HOMINGACTIONGOAL>"
   "HOMINGACTIONGOAL"
   "<HOMINGACTIONRESULT>"
   "HOMINGACTIONRESULT"
   "<HOMINGFEEDBACK>"
   "HOMINGFEEDBACK"
   "<HOMINGGOAL>"
   "HOMINGGOAL"
   "<HOMINGRESULT>"
   "HOMINGRESULT"
  ))

