; Auto-generated. Do not edit!


(cl:in-package dynamixel_ros_control-msg)


;//! \htmlinclude HomingResult.msg.html

(cl:defclass <HomingResult> (roslisp-msg-protocol:ros-message)
  ((done
    :reader done
    :initarg :done
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass HomingResult (<HomingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HomingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HomingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dynamixel_ros_control-msg:<HomingResult> is deprecated: use dynamixel_ros_control-msg:HomingResult instead.")))

(cl:ensure-generic-function 'done-val :lambda-list '(m))
(cl:defmethod done-val ((m <HomingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dynamixel_ros_control-msg:done-val is deprecated.  Use dynamixel_ros_control-msg:done instead.")
  (done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HomingResult>) ostream)
  "Serializes a message object of type '<HomingResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'done) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HomingResult>) istream)
  "Deserializes a message object of type '<HomingResult>"
    (cl:setf (cl:slot-value msg 'done) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HomingResult>)))
  "Returns string type for a message object of type '<HomingResult>"
  "dynamixel_ros_control/HomingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HomingResult)))
  "Returns string type for a message object of type 'HomingResult"
  "dynamixel_ros_control/HomingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HomingResult>)))
  "Returns md5sum for a message object of type '<HomingResult>"
  "89bb254424e4cffedbf494e7b0ddbfea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HomingResult)))
  "Returns md5sum for a message object of type 'HomingResult"
  "89bb254424e4cffedbf494e7b0ddbfea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HomingResult>)))
  "Returns full string definition for message of type '<HomingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HomingResult)))
  "Returns full string definition for message of type 'HomingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HomingResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HomingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'HomingResult
    (cl:cons ':done (done msg))
))
