; Auto-generated. Do not edit!


(cl:in-package dynamixel_ros_control-msg)


;//! \htmlinclude HomingFeedback.msg.html

(cl:defclass <HomingFeedback> (roslisp-msg-protocol:ros-message)
  ((is_moving
    :reader is_moving
    :initarg :is_moving
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass HomingFeedback (<HomingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HomingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HomingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dynamixel_ros_control-msg:<HomingFeedback> is deprecated: use dynamixel_ros_control-msg:HomingFeedback instead.")))

(cl:ensure-generic-function 'is_moving-val :lambda-list '(m))
(cl:defmethod is_moving-val ((m <HomingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dynamixel_ros_control-msg:is_moving-val is deprecated.  Use dynamixel_ros_control-msg:is_moving instead.")
  (is_moving m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HomingFeedback>) ostream)
  "Serializes a message object of type '<HomingFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'is_moving) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HomingFeedback>) istream)
  "Deserializes a message object of type '<HomingFeedback>"
    (cl:setf (cl:slot-value msg 'is_moving) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HomingFeedback>)))
  "Returns string type for a message object of type '<HomingFeedback>"
  "dynamixel_ros_control/HomingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HomingFeedback)))
  "Returns string type for a message object of type 'HomingFeedback"
  "dynamixel_ros_control/HomingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HomingFeedback>)))
  "Returns md5sum for a message object of type '<HomingFeedback>"
  "552aeb9cf1ea5fa2b0b9d933540d4e52")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HomingFeedback)))
  "Returns md5sum for a message object of type 'HomingFeedback"
  "552aeb9cf1ea5fa2b0b9d933540d4e52")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HomingFeedback>)))
  "Returns full string definition for message of type '<HomingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%bool is_moving~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HomingFeedback)))
  "Returns full string definition for message of type 'HomingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%bool is_moving~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HomingFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HomingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HomingFeedback
    (cl:cons ':is_moving (is_moving msg))
))
