// Generated by gencpp from file dynamixel_ros_control/HomingResult.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_ROS_CONTROL_MESSAGE_HOMINGRESULT_H
#define DYNAMIXEL_ROS_CONTROL_MESSAGE_HOMINGRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_ros_control
{
template <class ContainerAllocator>
struct HomingResult_
{
  typedef HomingResult_<ContainerAllocator> Type;

  HomingResult_()
    : done(false)  {
    }
  HomingResult_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> const> ConstPtr;

}; // struct HomingResult_

typedef ::dynamixel_ros_control::HomingResult_<std::allocator<void> > HomingResult;

typedef boost::shared_ptr< ::dynamixel_ros_control::HomingResult > HomingResultPtr;
typedef boost::shared_ptr< ::dynamixel_ros_control::HomingResult const> HomingResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_ros_control::HomingResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_ros_control::HomingResult_<ContainerAllocator1> & lhs, const ::dynamixel_ros_control::HomingResult_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_ros_control::HomingResult_<ContainerAllocator1> & lhs, const ::dynamixel_ros_control::HomingResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_ros_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::dynamixel_ros_control::HomingResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_ros_control/HomingResult";
  }

  static const char* value(const ::dynamixel_ros_control::HomingResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"bool done\n"
;
  }

  static const char* value(const ::dynamixel_ros_control::HomingResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomingResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_ros_control::HomingResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_ros_control::HomingResult_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_ROS_CONTROL_MESSAGE_HOMINGRESULT_H
